In [1]:
# IMPOERTS>>>
import numpy as np
import pandas as pd

In [2]:
# constants
VOCAB_SIZE = 2500
TRAINING_DATA_FILE = 'SpamData/02_Training/train-data.txt'
TEST_DATA_FILE = 'SpamData/02_Training/test-data.txt'

In [3]:
sparse_train_data = np.loadtxt(TRAINING_DATA_FILE, dtype= int, delimiter=' ')

In [4]:
type(sparse_train_data)

numpy.ndarray

In [5]:
sparse_train_data.shape

(258353, 4)

In [6]:
sparse_train_data[:5]

array([[ 0,  2,  1,  1],
       [ 0,  3,  1,  2],
       [ 0,  4,  1,  1],
       [ 0,  7,  1,  3],
       [ 0, 11,  1,  1]])

In [7]:
sparse_train_data[-5:]

array([[5795, 2035,    0,    1],
       [5795, 2041,    0,    2],
       [5795, 2277,    0,    1],
       [5795, 2334,    0,    1],
       [5795, 2357,    0,    1]])

In [8]:
sparse_test_data = np.loadtxt(TEST_DATA_FILE, dtype= int, delimiter=' ')

In [9]:
type(sparse_test_data)

numpy.ndarray

In [10]:
sparse_test_data.shape

(117772, 4)

In [11]:
sparse_test_data[:5]

array([[8, 2, 1, 1],
       [8, 3, 1, 4],
       [8, 4, 1, 2],
       [8, 5, 1, 1],
       [8, 6, 1, 2]])

In [12]:
print(' Number of rows  in the training file : ',sparse_train_data.shape[0] )
print(' Number of rows in the testing  data : ',sparse_test_data.shape[0] )

 Number of rows  in the training file :  258353
 Number of rows in the testing  data :  117772


In [13]:
print(' Number of rows  in the training file : ',sparse_train_data[:,2].size )
print(' Number of rows in the testing  data : ',sparse_test_data[:,0].size )

 Number of rows  in the training file :  258353
 Number of rows in the testing  data :  117772


In [14]:
np.unique(sparse_train_data[:,0]).size

4013

In [15]:
np.unique(sparse_test_data[:,0]).size

1724

In [16]:
# creating a dataframe....
# DOC_ID, CATEGORY, for ecah word in vocab_word there has to be one column....
column_names = ['DOC_ID'] + ['CATEGORY'] + list(range(0, VOCAB_SIZE))

In [17]:
column_names[:6]

['DOC_ID', 'CATEGORY', 0, 1, 2, 3]

In [18]:
column_names[-5:]

[2495, 2496, 2497, 2498, 2499]

In [19]:
len(column_names)

2502

In [20]:
index_names = np.unique(sparse_train_data[:,0])

In [21]:
index_names

array([   0,    1,    2, ..., 5791, 5794, 5795])

In [22]:
full_train_data = pd.DataFrame(index= index_names, columns= column_names)

In [23]:
full_train_data

DOC_ID CATEGORY    0    1    2    3    4    5    6    7  ... 2490 2491  \
0       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
1       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
2       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
3       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
4       NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
...     ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
5789    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5790    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5791    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5794    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   
5795    NaN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN   

     2492 2493 2494 2495 2496 2497 2498 2499  
0     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
2     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
...   ...  ...  ...  ...  ...  ...  ...  ...  
5789  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5790  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5791  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5794  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
5795  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[4013 rows x 2502 columns]

In [24]:
full_train_data.fillna(value= 0, inplace= True)

In [25]:
full_train_data

DOC_ID  CATEGORY  0  1  2  3  4  5  6  7  ...  2490  2491  2492  2493  \
0          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
1          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
2          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
3          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
4          0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
...      ...       ... .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
5789       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5790       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5791       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5794       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   
5795       0         0  0  0  0  0  0  0  0  0  ...     0     0     0     0   

      2494  2495  2496  2497  2498  2499  
0        0     0     0     0     0     0  
1        0     0     0     0     0     0  
2        0     0     0     0     0     0  
3        0     0     0     0     0     0  
4        0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
5789     0     0     0     0     0     0  
5790     0     0     0     0     0     0  
5791     0     0     0     0     0     0  
5794     0     0     0     0     0     0  
5795     0     0     0     0     0     0  

[4013 rows x 2502 columns]

In [26]:
sparse_train_data[:5]

array([[ 0,  2,  1,  1],
       [ 0,  3,  1,  2],
       [ 0,  4,  1,  1],
       [ 0,  7,  1,  3],
       [ 0, 11,  1,  1]])

In [27]:
# doc_idx = 0
# doc_nr = sparse_matrix[i][doc_idx]
doc_nr = sparse_train_data[0][0]
doc_nr

0

In [28]:
# word_idx=1 
#word_id = sparse_matrix[i][word_idx]
word_id = sparse_train_data[0][1]
word_id

2

In [29]:
# cat_idx=2
#label = sparse_matrix[i][cat_idx]
label = sparse_train_data[0][2]
label

1

In [30]:
# freq_idx=3
# occurrence = sparse_matrix[i][freq_idx]
occurrence =sparse_train_data[0][3]
occurrence

1

In [31]:
def make_full_matrix(sparse_matrix, nr_words, doc_idx=0, word_idx=1, cat_idx=2, freq_idx=3):
    
    column_names = ['DOC_ID']+['CATEGORY']+list(range(0,nr_words))
    doc_id_names = np.unique(sparse_matrix[:,0])
    full_matrix = pd.DataFrame(index= doc_id_names, columns= column_names)
    full_matrix.fillna(value= 0, inplace= True)
    
    for i in range(sparse_matrix.shape[0]):
        
        doc_nr = sparse_matrix[i][doc_idx]
        label  = sparse_matrix[i][cat_idx]
        word_id= sparse_matrix[i][word_idx]
        occurrence=sparse_matrix[i][freq_idx]
        
        full_matrix.at[doc_nr, 'DOC_ID'] = doc_nr
        full_matrix.at[doc_nr,'CATEGORY']= label
        full_matrix.at[doc_nr, word_id]  = occurrence
        
    full_matrix.set_index('DOC_ID', inplace= True)
    
    return full_matrix


In [32]:
full_train_data = make_full_matrix(sparse_train_data, nr_words= VOCAB_SIZE)

In [33]:
full_train_data

CATEGORY  0  1  2  3  4  5  6   7  8  ...  2490  2491  2492  2493  \
DOC_ID                                        ...                           
0              1  0  0  1  2  1  0  0   3  0  ...     0     0     0     0   
1              1  7  1  2  0  1  0  0   1  0  ...     0     0     0     0   
2              1  6  1  1  0  1  0  0   1  0  ...     0     0     0     0   
3              1  6  0  0  2  4  0  3  14  0  ...     0     0     0     0   
4              1  5  1  2  0  1  0  0   1  0  ...     0     0     0     0   
...          ... .. .. .. .. .. .. ..  .. ..  ...   ...   ...   ...   ...   
5789           0  3  1  0  1  0  0  0   1  0  ...     0     0     0     0   
5790           0  1  1  1  0  0  0  1   0  0  ...     0     0     0     0   
5791           0  3  1  0  1  1  0  0   0  1  ...     1     0     0     0   
5794           0  1  1  1  0  0  1  2   0  0  ...     0     0     0     0   
5795           0  3  4  2  0  5  0  3   0  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
0          0     0     0     0     0     0  
1          0     0     0     0     0     0  
2          0     0     0     0     0     0  
3          0     0     0     0     0     0  
4          0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...  
5789       0     0     0     0     0     0  
5790       0     0     0     0     0     0  
5791       0     0     0     0     0     0  
5794       0     0     0     0     0     0  
5795       0     0     0     0     0     0  

[4013 rows x 2501 columns]

In [34]:
email_lengths =full_train_data.CATEGORY.size
full_train_data.CATEGORY.size

4013

In [35]:
full_train_data.CATEGORY.sum()

1248

In [36]:
prob_spam = full_train_data.CATEGORY.sum()/full_train_data.CATEGORY.size
prob_spam

0.310989284824321

In [37]:
full_train_data.head()

CATEGORY  0  1  2  3  4  5  6   7  8  ...  2490  2491  2492  2493  \
DOC_ID                                        ...                           
0              1  0  0  1  2  1  0  0   3  0  ...     0     0     0     0   
1              1  7  1  2  0  1  0  0   1  0  ...     0     0     0     0   
2              1  6  1  1  0  1  0  0   1  0  ...     0     0     0     0   
3              1  6  0  0  2  4  0  3  14  0  ...     0     0     0     0   
4              1  5  1  2  0  1  0  0   1  0  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
0          0     0     0     0     0     0  
1          0     0     0     0     0     0  
2          0     0     0     0     0     0  
3          0     0     0     0     0     0  
4          0     0     0     0     0     0  

[5 rows x 2501 columns]

In [38]:
full_train_features = full_train_data.loc[:, full_train_data.columns != 'CATEGORY']

In [39]:
email_lengths = full_train_features.sum(axis =1)
email_lengths.shape

(4013,)

In [40]:
email_lengths

DOC_ID
0        87
1        53
2        40
3       183
4        43
       ... 
5789     18
5790     72
5791     46
5794     57
5795    264
Length: 4013, dtype: int64

In [41]:
total_wc = email_lengths.sum()
total_wc

429215

In [42]:
spam_lengths = email_lengths[full_train_data.CATEGORY == 1]
spam_lengths.shape

(1248,)

In [43]:
print(spam_lengths) 

DOC_ID
0        87
1        53
2        40
3       183
4        43
       ... 
1885     45
1887     26
1889    115
1890     26
1895    162
Length: 1248, dtype: int64


In [44]:
spam_wc = spam_lengths.sum()
spam_wc

176307

In [45]:
ham_lengths = email_lengths[full_train_data.CATEGORY == 0]
ham_lengths.shape

(2765,)

In [46]:
print(ham_lengths)

DOC_ID
1896     82
1898    112
1899     66
1900     49
1901     34
       ... 
5789     18
5790     72
5791     46
5794     57
5795    264
Length: 2765, dtype: int64


In [47]:
nonspam_wc = ham_lengths.sum()
nonspam_wc

252908

In [48]:
print('Number of words in non spam emails   ', nonspam_wc, '\n') # number of words in non spam mails
print('Number of words in  spam emails      ', spam_wc, '\n') # number of words in spam mail
print('Sum of words in ham and spam mails   ', nonspam_wc + spam_wc)

Number of words in non spam emails    252908 

Number of words in  spam emails       176307 

Sum of words in ham and spam mails    429215


In [49]:
# sum the token occurring in the spam mails....

In [50]:
full_train_features.shape

(4013, 2500)

In [51]:
full_train_features

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
0          0     0     1     2     1     0     0     3     0     0  ...     0   
1          7     1     2     0     1     0     0     1     0     0  ...     0   
2          6     1     1     0     1     0     0     1     0     0  ...     0   
3          6     0     0     2     4     0     3    14     0     0  ...     0   
4          5     1     2     0     1     0     0     1     0     0  ...     0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5789       3     1     0     1     0     0     0     1     0     0  ...     0   
5790       1     1     1     0     0     0     1     0     0     0  ...     0   
5791       3     1     0     1     1     0     0     0     1     0  ...     1   
5794       1     1     1     0     0     1     2     0     0     1  ...     0   
5795       3     4     2     0     5     0     3     0     0     4  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
0          0     0     0     0     0     0     0     0     0  
1          0     0     0     0     0     0     0     0     0  
2          0     0     0     0     0     0     0     0     0  
3          0     0     0     0     0     0     0     0     0  
4          0     0     0     0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
5789       0     0     0     0     0     0     0     0     0  
5790       0     0     0     0     0     0     0     0     0  
5791       0     0     0     0     0     0     0     0     0  
5794       0     0     0     0     0     0     0     0     0  
5795       0     0     0     0     0     0     0     0     0  

[4013 rows x 2500 columns]

In [59]:
train_spam_tokens = full_train_features.loc[full_train_data.CATEGORY == 1]
train_spam_tokens

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
0          0     0     1     2     1     0     0     3     0     0  ...     0   
1          7     1     2     0     1     0     0     1     0     0  ...     0   
2          6     1     1     0     1     0     0     1     0     0  ...     0   
3          6     0     0     2     4     0     3    14     0     0  ...     0   
4          5     1     2     0     1     0     0     1     0     0  ...     0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1885       1     0     0     2     0     1     0     0     0     0  ...     0   
1887       2     0     0     0     0     0     0     0     0     0  ...     0   
1889       0     0     0     0     0     0     0     0     1     0  ...     0   
1890       2     0     0     0     1     0     0     2     0     0  ...     0   
1895       1     1     1     0     0     0     0     0     0     0  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
0          0     0     0     0     0     0     0     0     0  
1          0     0     0     0     0     0     0     0     0  
2          0     0     0     0     0     0     0     0     0  
3          0     0     0     0     0     0     0     0     0  
4          0     0     0     0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
1885       0     0     0     0     0     0     0     0     0  
1887       0     0     0     0     0     0     0     0     0  
1889       0     0     0     0     0     0     0     0     0  
1890       0     0     0     0     0     0     0     0     0  
1895       0     0     0     0     0     0     0     0     0  

[1248 rows x 2500 columns]

In [54]:
summed_spam_tokens = train_spam_tokens.sum(axis=0) + 1  # Laplace Smoothing

In [55]:
summed_spam_tokens

0       2179
1        935
2       1217
3       2022
4       1219
        ... 
2495      10
2496       1
2497       1
2498       2
2499       6
Length: 2500, dtype: int64

In [56]:
type(summed_spam_tokens)

pandas.core.series.Series

In [57]:
# sum the token occurring in the ham mails....

In [60]:
train_ham_tokens = full_train_features.loc[full_train_data.CATEGORY == 0]
train_ham_tokens

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
1896       1     2     1     0     1     1     2     0     1     1  ...     0   
1898       2     1     0     1     1     0     2     1     0     0  ...     0   
1899       2     1     1     0     0     1     1     0     1     0  ...     0   
1900       3     4     0     1     0     0     1     1     1     1  ...     0   
1901       2     2     0     1     0     0     1     1     0     0  ...     0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5789       3     1     0     1     0     0     0     1     0     0  ...     0   
5790       1     1     1     0     0     0     1     0     0     0  ...     0   
5791       3     1     0     1     1     0     0     0     1     0  ...     1   
5794       1     1     1     0     0     1     2     0     0     1  ...     0   
5795       3     4     2     0     5     0     3     0     0     4  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
1896       0     0     0     0     0     0     0     0     0  
1898       0     0     0     0     0     0     0     0     0  
1899       0     0     0     0     0     0     0     0     0  
1900       0     0     0     0     0     0     0     0     0  
1901       0     0     0     0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
5789       0     0     0     0     0     0     0     0     0  
5790       0     0     0     0     0     0     0     0     0  
5791       0     0     0     0     0     0     0     0     0  
5794       0     0     0     0     0     0     0     0     0  
5795       0     0     0     0     0     0     0     0     0  

[2765 rows x 2500 columns]

In [61]:
summed_ham_tokens = train_ham_tokens.sum(axis=0) + 1
summed_ham_tokens

0       5484
1       2590
2       2045
3        938
4       1612
        ... 
2495      24
2496       6
2497      33
2498      23
2499      25
Length: 2500, dtype: int64

In [62]:
prob_tokens_spam = summed_spam_tokens / (spam_wc + VOCAB_SIZE)  # Laplace Smoothing

In [63]:
prob_tokens_spam

0       0.012186
1       0.005229
2       0.006806
3       0.011308
4       0.006817
          ...   
2495    0.000056
2496    0.000006
2497    0.000006
2498    0.000011
2499    0.000034
Length: 2500, dtype: float64

In [66]:
prob_tokens_spam.sum(axis=0)

1.0

### P(Loan|ham) think as an Example.....P(Token|ham)......

In [67]:
prob_tokens_nonspam = summed_ham_tokens / (nonspam_wc + VOCAB_SIZE)
prob_tokens_nonspam 

0       0.021472
1       0.010141
2       0.008007
3       0.003673
4       0.006311
          ...   
2495    0.000094
2496    0.000023
2497    0.000129
2498    0.000090
2499    0.000098
Length: 2500, dtype: float64

In [68]:
prob_tokens_nonspam.sum()

1.0

### P(Token).....that means a token occurs in both spam and ham......

In [69]:
prob_tokens_all = full_train_features.sum(axis=0) / total_wc
prob_tokens_all 

0       0.017849
1       0.008208
2       0.007595
3       0.006892
4       0.006591
          ...   
2495    0.000075
2496    0.000012
2497    0.000075
2498    0.000054
2499    0.000068
Length: 2500, dtype: float64

In [70]:
prob_tokens_all.sum()

1.0

In [71]:
# save the trained model......

In [72]:
TOKEN_SPAM_PROB_FILE = 'SpamData/03_Testing/prob-spam.txt'
TOKEN_HAM_PROB_FILE = 'SpamData/03_Testing/prob-nonspam.txt'
TOKEN_ALL_PROB_FILE = 'SpamData/03_Testing/prob-all-tokens.txt'

In [73]:
np.savetxt(TOKEN_SPAM_PROB_FILE, prob_tokens_spam)
np.savetxt(TOKEN_HAM_PROB_FILE, prob_tokens_nonspam)
np.savetxt(TOKEN_ALL_PROB_FILE, prob_tokens_all)

In [74]:
# prepare the Test data.....

In [75]:
sparse_test_data.shape

(117772, 4)

In [76]:
full_test_data = make_full_matrix(sparse_test_data, nr_words=VOCAB_SIZE)
full_test_data

CATEGORY  0  1  2  3  4  5  6  7  8  ...  2490  2491  2492  2493  \
DOC_ID                                       ...                           
8              1  0  0  1  4  2  1  2  4  1  ...     0     0     0     0   
12             1  6  1  1  0  1  0  0  1  0  ...     0     0     0     0   
14             1  0  0  1  1  0  0  0  0  0  ...     0     0     0     0   
15             1  0  2  1  1  2  0  0  3  0  ...     0     0     0     0   
17             1  0  0  0  0  1  0  1  0  0  ...     0     0     0     0   
...          ... .. .. .. .. .. .. .. .. ..  ...   ...   ...   ...   ...   
5783           0  2  1  0  2  0  0  0  0  0  ...     0     0     0     0   
5786           0  5  5  2  2  1  2  0  0  1  ...     0     0     0     0   
5788           0  0  4  0  2  4  3  3  1  4  ...     0     0     0     0   
5792           0  2  2  0  1  0  0  2  1  0  ...     0     0     0     0   
5793           0  1  9  1  0  0  1  2  1  1  ...     0     0     0     0   

        2494  2495  2496  2497  2498  2499  
DOC_ID                                      
8          0     0     0     0     0     0  
12         0     0     0     0     0     0  
14         0     0     0     0     0     0  
15         0     0     0     0     0     0  
17         0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...  
5783       0     0     0     0     0     0  
5786       0     0     0     0     0     0  
5788       0     0     0     0     0     0  
5792       0     0     0     0     0     0  
5793       0     0     0     0     0     0  

[1724 rows x 2501 columns]

In [77]:
X_test = full_test_data.loc[:, full_test_data.columns != 'CATEGORY']

In [78]:
X_test

0     1     2     3     4     5     6     7     8     9     ...  2490  \
DOC_ID                                                              ...         
8          0     0     1     4     2     1     2     4     1     2  ...     0   
12         6     1     1     0     1     0     0     1     0     0  ...     0   
14         0     0     1     1     0     0     0     0     0     0  ...     0   
15         0     2     1     1     2     0     0     3     0     4  ...     0   
17         0     0     0     0     1     0     1     0     0     0  ...     0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
5783       2     1     0     2     0     0     0     0     0     0  ...     0   
5786       5     5     2     2     1     2     0     0     1     0  ...     0   
5788       0     4     0     2     4     3     3     1     4     3  ...     0   
5792       2     2     0     1     0     0     2     1     0     0  ...     0   
5793       1     9     1     0     0     1     2     1     1     1  ...     0   

        2491  2492  2493  2494  2495  2496  2497  2498  2499  
DOC_ID                                                        
8          0     0     0     0     0     0     0     0     0  
12         0     0     0     0     0     0     0     0     0  
14         0     0     0     0     0     0     0     0     0  
15         0     0     0     0     0     0     0     0     0  
17         0     0     0     0     0     0     0     0     0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
5783       0     0     0     0     0     0     0     0     0  
5786       0     0     0     0     0     0     0     0     0  
5788       0     0     0     0     0     0     0     0     0  
5792       0     0     0     0     0     0     0     0     0  
5793       0     0     0     0     0     0     0     0     0  

[1724 rows x 2500 columns]

In [79]:
y_test = full_test_data.CATEGORY
y_test

DOC_ID
8       1
12      1
14      1
15      1
17      1
       ..
5783    0
5786    0
5788    0
5792    0
5793    0
Name: CATEGORY, Length: 1724, dtype: int64

In [80]:
TEST_FEATURE_MATRIX = 'SpamData/03_Testing/test-features.txt'
TEST_TARGET_FILE = 'SpamData/03_Testing/test-target.txt'

In [81]:
np.savetxt(TEST_FEATURE_MATRIX, X_test)
np.savetxt(TEST_TARGET_FILE, y_test)